### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by justintaeson** [justintaeson/driving-game#1]
Open a new Issue on your GitHub repository with the title User can see their car and paste the following block of [Markdown](https://guides.github.com/features/mastering-markdown/) into the comment box.

You will attempt to write your own task list before coding this feature. Refer to past projects for an example of what a task list should look like. Lots of small tasks is better than a few large tasks.

## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML skeleton.
- [x] Style the background to be green.
- [x] Create the image of the car.
