### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by justintaeson** [justintaeson/driving-game#3]
Open a new Issue on your GitHub repository with the title User can turn their car and paste the following block of [Markdown](https://guides.github.com/features/mastering-markdown/) into the comment box.

You will attempt to write your own task list before coding this feature. Refer to past projects for an example of what a task list should look like. Lots of small tasks is better than a few large tasks.

## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [ ] Create a data model to track where the car is facing.
- [ ] Add an event listener for 'keydown' events on the document.
- [ ] Add functionality to turn the car when the arrows keys are pressed.
